export const rooms = [
  {
    id: 1,
    title: "Standard Twin Room",
    description: "Perfect for sharing, featuring two comfortable single beds",
    price: 199,
    size: "28m²",
    occupancy: "2 Adults",
    beds: "2 Single Beds",
    image: "https://picsum.photos/seed/room1/800/500",
    amenities: ["wifi", "tv", "shower", "coffee"],
    additionalImages: [
      "https://picsum.photos/seed/room1a/800/500",
      "https://picsum.photos/seed/room1b/800/500",
      "https://picsum.photos/seed/room1c/800/500",
    ],
    features: [
      "Daily housekeeping",
      "Air conditioning",
      "In-room safe",
      "Mini fridge",
      "Desk & chair",
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      cancellation: "24 hours before arrival",
      children: "Up to 1 child under 12 stays free",
      pets: "Not allowed",
    },
  },
  {
    id: 2,
    title: "Standard Room",
    description: "Cozy room with a queen-size bed and modern amenities",
    price: 249,
    size: "32m²",
    occupancy: "2 Adults",
    beds: "1 Queen Bed",
    image: "https://picsum.photos/seed/room2/800/500",
    amenities: ["wifi", "tv", "shower", "coffee", "minibar"],
    additionalImages: [
      "https://picsum.photos/seed/room2a/800/500",
      "https://picsum.photos/seed/room2b/800/500",
      "https://picsum.photos/seed/room2c/800/500",
    ],
    features: [
      "Daily housekeeping",
      "Air conditioning",
      "In-room safe",
      "Mini fridge",
      "Desk & chair",
      "Lounge chair",
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      cancellation: "24 hours before arrival",
      children: "Up to 1 child under 12 stays free",
      pets: "Not allowed",
    },
  },
  {
    id: 3,
    title: "Standard View Room",
    description: "Stunning city views with deluxe furnishings",
    price: 299,
    size: "35m²",
    occupancy: "2 Adults, 1 Child",
    beds: "1 King Bed",
    image: "https://picsum.photos/seed/room3/800/500",
    amenities: ["wifi", "tv", "shower", "coffee", "minibar", "workspace"],
    additionalImages: [
      "https://picsum.photos/seed/room3a/800/500",
      "https://picsum.photos/seed/room3b/800/500",
      "https://picsum.photos/seed/room3c/800/500",
    ],
    features: [
      "Daily housekeeping",
      "Air conditioning",
      "In-room safe",
      "Mini fridge",
      "Desk & chair",
      "Lounge area",
      "City view",
    ],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "48 hours before arrival",
      children: "Up to 1 child under 12 stays free",
      pets: "Not allowed",
    },
  },
  {
    id: 4,
    title: "Deluxe Room",
    description: "Spacious luxury with premium amenities and services",
    price: 399,
    size: "45m²",
    occupancy: "2 Adults, 2 Children",
    beds: "1 King Bed, 1 Sofa Bed",
    image: "https://picsum.photos/seed/room4/800/500",
    amenities: [
      "wifi",
      "tv",
      "shower",
      "coffee",
      "minibar",
      "workspace",
      "bathtub",
    ],
    additionalImages: [
      "https://picsum.photos/seed/room4a/800/500",
      "https://picsum.photos/seed/room4b/800/500",
      "https://picsum.photos/seed/room4c/800/500",
    ],
    features: [
      "Daily housekeeping",
      "Air conditioning",
      "In-room safe",
      "Mini fridge",
      "Executive desk",
      "Lounge area",
      "Premium view",
      "Nespresso machine",
      "Premium toiletries",
    ],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "2:00 PM",
      cancellation: "72 hours before arrival",
      children: "Up to 2 children under 12 stay free",
      pets: "Small pets allowed (extra charge)",
    },
  },
];

export const amenityIcons = {
  wifi: { icon: "lucide:wifi", label: "Free WiFi" },
  tv: { icon: "lucide:tv", label: "Smart TV" },
  shower: { icon: "lucide:shower-head", label: "Rain Shower" },
  coffee: { icon: "lucide:coffee", label: "Coffee Maker" },
  minibar: { icon: "lucide:wine", label: "Mini Bar" },
  workspace: { icon: "lucide:laptop", label: "Work Space" },
  bathtub: { icon: "lucide:bath", label: "Bathtub" },
};
